In [2]:
import pandas as pd
import numpy as np

In [14]:
m_d=pd.read_csv(r"Movie.csv")

In [16]:
m_d

      userId             movie  rating
0          3  Toy Story (1995)     4.0
1          6  Toy Story (1995)     5.0
2          8  Toy Story (1995)     4.0
3         10  Toy Story (1995)     4.0
4         11  Toy Story (1995)     4.5
...      ...               ...     ...
8987    7087  GoldenEye (1995)     3.0
8988    7088  GoldenEye (1995)     1.0
8989    7105  GoldenEye (1995)     2.0
8990    7113  GoldenEye (1995)     3.0
8991    7117  GoldenEye (1995)     3.0

[8992 rows x 3 columns]

In [18]:
m_d.shape

(8992, 3)

In [20]:
m_d[0:5]

   userId             movie  rating
0       3  Toy Story (1995)     4.0
1       6  Toy Story (1995)     5.0
2       8  Toy Story (1995)     4.0
3      10  Toy Story (1995)     4.0
4      11  Toy Story (1995)     4.5

In [28]:
m_d[m_d['userId']==11]

      userId             movie  rating
4         11  Toy Story (1995)     4.5
7446      11  GoldenEye (1995)     2.5

In [34]:
unique_userid=m_d['userId'].unique()
unique_userid

array([   3,    6,    8, ..., 7080, 7087, 7105])

In [36]:
len(unique_userid)

4081

In [42]:
unique_movie=m_d['movie'].unique()
unique_movie

array(['Toy Story (1995)', 'Jumanji (1995)', 'Grumpier Old Men (1995)',
       'Waiting to Exhale (1995)', 'Father of the Bride Part II (1995)',
       'Heat (1995)', 'Sabrina (1995)', 'Tom and Huck (1995)',
       'Sudden Death (1995)', 'GoldenEye (1995)'], dtype=object)

In [44]:
len(unique_movie)

10

In [48]:
#user interaction matrix
m_d.isnull().sum()

userId    0
movie     0
rating    0
dtype: int64

In [71]:
#to create table as below 
user_movie_d=m_d.pivot(index='userId',columns='movie',values='rating').reset_index(drop=True)#creates user item interaction matrix

In [73]:
user_movie_d

movie,Father of the Bride Part II (1995),GoldenEye (1995),Grumpier Old Men (1995),Heat (1995),Jumanji (1995),Sabrina (1995),Sudden Death (1995),Tom and Huck (1995),Toy Story (1995),Waiting to Exhale (1995)
0,NaN,NaN,NaN,NaN,3.5,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN
3,NaN,4.0,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
4076,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4077,3.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN
4078,NaN,3.0,4.0,5.0,NaN,3.0,1.0,NaN,4.0,NaN
4079,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN
4080,NaN,NaN,NaN,NaN,4.0,4.0,NaN,NaN,4.5,NaN

In [78]:
#to find similarities between the customers
#cosine matrix
#correlation coefficient 
#Ecludian 
#Manahatton
user_movie_d.index=m_d.userId.unique()

In [80]:
user_movie_d

movie,Father of the Bride Part II (1995),GoldenEye (1995),Grumpier Old Men (1995),Heat (1995),Jumanji (1995),Sabrina (1995),Sudden Death (1995),Tom and Huck (1995),Toy Story (1995),Waiting to Exhale (1995)
3,NaN,NaN,NaN,NaN,3.5,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN
10,NaN,4.0,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
7044,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7070,3.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN
7080,NaN,3.0,4.0,5.0,NaN,3.0,1.0,NaN,4.0,NaN
7087,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN
7105,NaN,NaN,NaN,NaN,4.0,4.0,NaN,NaN,4.5,NaN

In [84]:
user_movie_d.fillna(0)

movie,Father of the Bride Part II (1995),GoldenEye (1995),Grumpier Old Men (1995),Heat (1995),Jumanji (1995),Sabrina (1995),Sudden Death (1995),Tom and Huck (1995),Toy Story (1995),Waiting to Exhale (1995)
3,0.0,0.0,0.0,0.0,3.5,0.0,0.0,0.0,0.0,0.0
6,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0
10,0.0,4.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0
11,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...
7044,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7070,3.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0
7080,0.0,3.0,4.0,5.0,0.0,3.0,1.0,0.0,4.0,0.0
7087,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0
7105,0.0,0.0,0.0,0.0,4.0,4.0,0.0,0.0,4.5,0.0